FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY secondary.py .

EXPOSE 5001

ENV REPLICATION_DELAY=1

CMD ["python", "secondary.py"]
